# Generated by Django 5.1 on 2024-08-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangolib", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ebooksmodel",
            name="epub",
            field=models.FileField(blank=True, null=True, upload_to="texts/epub/"),
        ),
        migrations.AddField(
            model_name="ebooksmodel",
            name="fb2",
            field=models.FileField(blank=True, null=True, upload_to="texts/fb2/"),
        ),
        migrations.AlterField(
            model_name="ebooksmodel",
            name="txt",
            field=models.FileField(
                upload_to="texts/txt/", verbose_name="Загрузите файл"
            ),
        ),
    ]
