# Generated by Django 5.1 on 2024-08-19 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangolib", "0002_favoritebook"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FavoriteBook",
            new_name="FavouriteBook",
        ),
    ]
