# Generated by Django 5.1 on 2024-08-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangolib", "0002_alter_author_options_alter_ebooksmodel_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ebooksmodel",
            old_name="pdf",
            new_name="txt",
        ),
    ]
